### 
POST http://localhost:3000/signin/
Content-Type: application/json

{
    "id":"909",
    "password":"11"
}

###
###
POST http://localhost:3000/signin/new_token/
Content-Type: application/json

{
    "refreshToken":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIzLCJpYXQiOjE2MDA1MjE2OTcsImV4cCI6MTYwMDUyMjI5N30.XPFhXOjwB-euEA2tevWLc8JLrZK19QiohF7hkl_hcfs"
}
###
### 
POST http://localhost:3000/signup/
Content-Type: application/json

{
    "id":"909",
    "password":"11"
}

###
###
GET http://localhost:3000/info
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjI0LCJpYXQiOjE2MDA1OTExMzksImV4cCI6MTYwMDU5MTczOX0.NgyFEDVmqJHlOEBoOAH0dzstnfH3WmKHi89xL3GSlHg
###
###
GET http://localhost:3000/logout
